shortname: xiayfblackwhite
permalink: /:year/:month/:day/:title
title: 黑*白
author: youngsterxyf
email: youngsterxyf@gmail.com
domain: youngsterxyf.github.com
pygments: true
safe: true
lsi: false
url: http://youngsterxyf.github.com
